# Generated by Django 6.0.1 on 2026-02-14 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaults',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer')], default='CONTRIBUTOR', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_memberships', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='vaults.vault')),
            ],
            options={
                'db_table': 'vault_memberships',
            },
        ),
        migrations.AddField(
            model_name='vault',
            name='members',
            field=models.ManyToManyField(related_name='vaults', through='vaults.VaultMembership', through_fields=('vault', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vaults.vault')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vault', '-created_at'], name='audit_logs_vault_i_e387aa_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vaultmembership',
            index=models.Index(fields=['vault', 'role'], name='vault_membe_vault_i_d4e903_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultmembership',
            index=models.Index(fields=['user'], name='vault_membe_user_id_6182c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaultmembership',
            unique_together={('vault', 'user')},
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['owner', 'is_archived'], name='vaults_owner_i_72b3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['created_at'], name='vaults_created_ac1a74_idx'),
        ),
    ]
