# Generated by Django 6.0.1 on 2026-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0002_add_search_vector_to_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='ai_insights_cache',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='ai_insights_updated_at',
        ),
    ]
