# Generated by Django 6.0.1 on 2026-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0003_remove_vault_ai_insights_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='ai_insights_cache',
            field=models.JSONField(blank=True, help_text='AI-generated vault insights: {themes[], research_gaps[], cross_references[], suggested_searches[], generated_at}', null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='ai_insights_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last AI insights generation', null=True),
        ),
    ]
