# Generated by Django 6.0.1 on 2026-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0004_vault_ai_insights_cache_vault_ai_insights_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultmembership',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user last accessed this vault', null=True),
        ),
    ]
