# Generated by Django 6.0.1 on 2026-02-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0005_vaultmembership_last_accessed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='default_citation_format',
            field=models.CharField(blank=True, choices=[('apa7', 'APA 7th Edition'), ('mla9', 'MLA 9th Edition'), ('chicago17', 'Chicago 17th Edition'), ('bibtex', 'BibTeX'), ('ieee', 'IEEE'), ('harvard', 'Harvard')], help_text='Default citation format for this vault (overrides user preference)', max_length=20, null=True),
        ),
    ]
