# Generated by Django 6.0.1 on 2026-02-14 17:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_add_search_vector_to_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
