# Generated by Django 6.0.1 on 2026-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_annotation_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='position',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
