# Generated by Django 6.0.1 on 2026-02-14 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultStorageUsage',
            fields=[
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage_usage', serialize=False, to='vaults.vault')),
                ('total_bytes', models.BigIntegerField(default=0, help_text='Total storage used in bytes')),
                ('file_count', models.IntegerField(default=0, help_text='Number of non-deleted files')),
                ('user_breakdown', models.JSONField(default=dict, help_text='Storage breakdown by user ID: {user_id: bytes}')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vault_storage_usage',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('URL', 'URL'), ('PDF', 'PDF'), ('BOOK', 'Book'), ('JOURNAL', 'Journal'), ('DATASET', 'Dataset')], default='URL', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='vaults.vault')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='vaults/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('pdf_title', models.CharField(blank=True, max_length=500)),
                ('pdf_author', models.CharField(blank=True, max_length=255)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploads', to='vaults.vault')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_uploads', to='sources.source')),
            ],
            options={
                'db_table': 'pdf_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['vault', 'is_deleted'], name='sources_sou_vault_i_1a9a86_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='sources_sou_source__5290ea_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['created_at'], name='sources_sou_created_5ab94d_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vault', 'url'), name='unique_active_source_per_vault'),
        ),
        migrations.AddIndex(
            model_name='pdfupload',
            index=models.Index(fields=['vault', 'deleted_at'], name='pdf_uploads_vault_i_fc0539_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfupload',
            index=models.Index(fields=['uploaded_by', 'deleted_at'], name='pdf_uploads_uploade_8cfd29_idx'),
        ),
    ]
