# Generated by Django 6.0.1 on 2026-02-14 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('vaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultStorageUsage',
            fields=[
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage_usage', serialize=False, to='vaults.vault')),
                ('total_bytes', models.BigIntegerField(default=0, help_text='Total storage used in bytes')),
                ('file_count', models.IntegerField(default=0, help_text='Number of non-deleted files')),
                ('user_breakdown', models.JSONField(default=dict, help_text='Storage breakdown by user ID: {user_id: bytes}')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vault_storage_usage',
            },
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploads', to='vaults.vault'),
        ),
        migrations.AddField(
            model_name='source',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='vaults.vault'),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_uploads', to='sources.source'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['vault', 'is_deleted'], name='sources_sou_vault_i_1a9a86_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='sources_sou_source__5290ea_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['created_at'], name='sources_sou_created_5ab94d_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vault', 'url'), name='unique_active_source_per_vault'),
        ),
        migrations.AddIndex(
            model_name='pdfupload',
            index=models.Index(fields=['vault', 'deleted_at'], name='pdf_uploads_vault_i_fc0539_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfupload',
            index=models.Index(fields=['uploaded_by', 'deleted_at'], name='pdf_uploads_uploade_8cfd29_idx'),
        ),
    ]
