# Generated by Django 6.0.1 on 2026-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
