# Generated by Django 6.0.1 on 2026-02-14 17:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_pdfupload_extracted_text'),
        ('vaults', '0002_add_search_vector_to_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text='AI-generated summary: {abstract, key_findings[], methodology, limitations, keywords[], generated_at}', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='source',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='source_search_vector_idx'),
        ),
    ]
