# Generated by Django 6.0.1 on 2026-02-14 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_add_search_vector_to_source'),
        ('vaults', '0005_vaultmembership_last_accessed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='vaults/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='vaults.vault')),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['vault', 'deleted_at'], name='file_upload_vault_i_451870_idx'), models.Index(fields=['uploaded_by', 'deleted_at'], name='file_upload_uploade_aec7d5_idx'), models.Index(fields=['file_type'], name='file_upload_file_ty_ea3dfb_idx')],
            },
        ),
    ]
