# Generated by Django 6.0.1 on 2026-02-14 17:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
