# Generated by Django 6.0.1 on 2026-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_alter_source_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
