# Generated by Django 6.0.1 on 2026-02-14 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreferences'),
        ('vaults', '0005_vaultmembership_last_accessed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_vaults', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_users', to='vaults.vault')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'vault'], name='notificatio_user_id_d580b7_idx')],
                'unique_together': {('user', 'vault')},
            },
        ),
    ]
