# Generated by Django 6.0.1 on 2026-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_mutedvault'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
