# Generated by Django 6.0.1 on 2026-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_path',
            field=models.CharField(blank=True, choices=[('guided', 'Guided'), ('demo', 'Demo'), ('skipped', 'Skipped')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
