# Generated by Django 6.0.1 on 2026-02-14 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_onboarding_completed_user_onboarding_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_notifications', models.BooleanField(default=True, help_text='Receive notifications about vault activity')),
                ('marketing_emails', models.BooleanField(default=True, help_text='Receive product updates and newsletters')),
                ('unsubscribe_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_preferences',
            },
        ),
    ]
