# Generated by Django 6.0.1 on 2026-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_citation_format',
            field=models.CharField(blank=True, choices=[('apa7', 'APA 7th Edition'), ('mla9', 'MLA 9th Edition'), ('chicago17', 'Chicago 17th Edition'), ('bibtex', 'BibTeX'), ('ieee', 'IEEE'), ('harvard', 'Harvard')], help_text='Default citation format for all vaults', max_length=20, null=True),
        ),
    ]
