# Generated by Django 6.0.1 on 2026-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64)),
                ('query_normalized', models.CharField(max_length=255)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'db_table': 'search_analytics',
                'ordering': ['-search_count', '-last_searched'],
                'constraints': [models.UniqueConstraint(fields=('query_hash',), name='unique_query_hash')],
            },
        ),
    ]
